config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  scope ":locale" do

    resources :posts do
      resources :comments
    end

    resources :projects do
      resources :comments
    end
  end

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author, :author_email,
                  :author_url, :content, :referrer,
                  :user_agent, :user_ip, :post_id,
                  :commentable_id, :commentable_type

  belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :published,
                  :author_id, :image
  belongs_to :author, class_name: "User"
  has_many :comments, as: :commentable
  validates :title, length: { in: 4..255 }
  scope :published, where(published: true)
  translates :name, :content

  def authored_by?(user)
    author == user
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :technologies_used, :published
  belongs_to :author, class_name: "User"
  has_many :comments, as: :commentable
  validates :name, length: { in: 4..255 }
  validates :technologies_used, presence: true
  scope :published, where(published: true)

  def authored_by?(user)
    author == user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role, :name
  # attr_accessible :title, :body
  has_many :posts, foreign_key: "author_id"
  has_many :projects, foreign_key: "author_id"

  def author?
    role == 'author'
  end

  def editor?
    role == 'editor'
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.nickname
      user.email = "#{user.name}-CHANGEME@twitter.example.com"
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  before_filter :set_locale
  before_filter :get_posts

  protected

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    { :locale => I18n.locale }
  end

  def get_posts
    @posts ||= Post.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_commentable

  def create
    @comment = @commentable.comments.new(params[:comment])
    if @comment.save
      redirect_to @commentable
    else
      instance_variable_set("@#{@resource.singularize}".to_sym, @commentable)
      render template: "#{@resource}/show"
    end
  end

  def destroy
    @comment = @commentable.comments.find(params[:id])
    authorize @comment
    @comment.destroy
    redirect_to @commentable, notice: 'Comment has been destroyed.'
  end

  def update
    @comment = @commentable.comments.find(params[:id])
    authorize @comment

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @commentable, notice: 'Comment has been approved.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


private

  def load_commentable
    @resource, id = request.path.split('/')[1,2]
    @commentable = @resource.singularize.classify.constantize.find(id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "#{user.name}, you are signed in!"
      sign_in_and_redirect user, notice: "#{user.name}, you are signed in!"
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @commentable = @post
    @comments = @commentable.comments
    @comments = policy_scope(Comment)
    @comment = Comment.new
    render :layout => "post_show"
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    render :layout => "post_create"
  end

  # GET /posts/1/edit
  def edit
    render :layout => "post_edit"
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    respond_to do |format|
      if @post.save
        current_user.posts << @post
        format.html { redirect_to "/" }
      else
        format.html { redirect_to "/" }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to "/" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    redirect_to "/"
  end

private
  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @projects = policy_scope(Project)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    authorize @project
    respond_to do |format|
      if @project.save
        current_user.projects << @project
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @projects }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @commentable = @project
    @comments = @commentable.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  def edit
    authorize @project
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @project
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

private
  def set_project
    @project = Project.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

 # translate the rails flash levels to appropriate twitter bootstrap css classes def flash_class(level)
 def flash_class(level)
  case level
   when :notice then "alert alert-info"
   when :success then "alert alert-success"
   when :error then "alert alert-error"
   when :alert then "alert alert-error"
  end
 end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    devise_mapping.to
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def me?
    user_signed_in? && current_user.name = "JonFriese33"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/_form.html.erb
<%= form_for([@commentable, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br />
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :Comment %><br />
    <%= f.text_area(:content, rows: 5) %>
  </div>

  <%= f.hidden_field :referrer, value: request.referrer %>
  <%= f.hidden_field :commentable_id, value: @commentable.id %>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/contact/index.html.erb
<h1>Contact Me!</h1>

app/views/home/_about.html.erb
<section>
  <div class="bl-box">
    <h2 >Hi My Name Is Jon</h2> <!-- class="bl-icon bl-icon-about" -->
  </div><!-- /bl-box -->
  <div class="bl-content">
    <div class="row-fluid">
      <div class="span12">
        <h2>A Little About Me</h2>
        <p>I'm a web developer living in Seattle</p>
        <p>I am a graduate of CodeFellows, an 8-week intensive bootcamp designed to take
        talented, motivated individuals and turn them into Rails developers. I'm currently working with PetChance.org to migrate their site from Rails 2 to Rails 3, as well as add new features. I like to solve challenging problems and work on interesting things.</p>
        <p></p>
        <p></p>
        <p></p>
        <div class="row-fluid">
          <div class="span8">
            <h2>My Skills</h2>
            <!-- Progress Bar -->
            <div class="progress">
              <div class="bar" style="width: 80%;">Javascript 80%</div>
            </div>
            <div class="progress">
              <div class="bar" style="width: 90%;">Ruby on Rails 90%</div>
            </div>
            <div class="progress">
              <div class="bar" style="width: 94%;">Behavior Driven Development 94%</div>
            </div>
            <div class="progress">
              <div class="bar" style="width: 87%;">Git/GitHub 87%</div>
            </div>
            <div class="progress">
              <div class="bar" style="width: 76%;">Agile Web Development 76%</div>
            </div>
            <!-- Progress Bar End -->
          </div><!-- /span6 -->
          <div class="span4"></div>
          <div class="span12">
            <br>
            <br>
          </div>
          <div class="span12">
            <div class="row about-us">
              <div class="span3">
                <!-- <h3><i class="icon-user icon-white"></i> More About Me?</h3>
                I enjoy visting and experiencing new places and cultures. I watch a lot of Netflix and I love to play basketball. -->
              </div>
              <div class="span3">
                <!-- <h3><i class="icon-heart icon-white"></i> What I Love</h3>
                Claritas est etiam processus dynamicus, and mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc. Parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima. -->
              </div>
              <div class="span3">
               <!--  <h3><i class="icon-fire icon-white"></i> Work Hard</h3>
                Claritas est etiam processus dynamicus, and mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc. Parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima. -->
              </div>
              <div class="span3">
                <!-- <h3><i class="icon-plane icon-white"></i> Ready To Go</h3>
                Claritas est etiam processus dynamicus, and mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc. Parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima. -->
              </div>
            </div><!-- /row-about-us -->
          </div><!-- /span12 -->
        </div><!-- /row -->
      </div><!-- /span12 -->
    </div><!-- /row-fluid -->

  </div><!-- /bl-content -->
  <span class="bl-icon bl-icon-close"></span>
</section>

app/views/home/_blog.html.erb
<section id="blog">
  <div class="bl-box">
    <h2>My Blog</h2>
  </div>
  <div class="bl-content">
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <%= current_user.name %>
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'signout' %>
        <% else %>
          <%- resource_class.omniauth_providers.each do |provider| %>
            <%= link_to image_tag("sign_in_twitter.png", alt:'twitter', id:"twitter"), omniauth_authorize_path(resource_name, provider) %>
          <% end -%>
        <% end %>
      </ul>
    </div> <!-- /.navbar-collapse -->
    <div class="row-fluid">
      <div class="span12">
        <% if me? %>
          <%= link_to 'Create Post', new_post_path %>
        <% end %>
        <h2>Blog Entries</h2>
        <h1><u>Multiple Nested Resources</u><h1>
        <p style="font-size:20px">If you are only beginning to learn Rails it may seem intuitive to have deeply nested routes to match your deeply nested resources. However, in Rails that isn’t necessary and is considered a bad practice. Your routes should not be nested more than once. Rails make it very easy to nest more than two resources without creating messy URLs and forms.

        This is an example of the incorrect way to use nested resources:</p>
        <%= image_tag "3deepbad.png" %>
        <p style="font-size:20px">This is how you should refactor the above routes.rb file:</p>
        <%= image_tag "3deepgood.png" %>
        <p style="font-size:20px">Making this small change will make everything you do with your routes so much easier as you continue to develop your project. Using form_for for deeply nested resources is now as simple as having two nested resources. You only have to reference the two youngest resources. As all the other relevant data is already contained in second youngest resource.</p>


        <% @posts.reverse_each do |post| %>
        <article>
          <h3><%= post.title %></h3>
          <p><%= truncate post.body, length:300 %>
          <span class="timestamp"><%=l post.created_at %></span>
          <%= image_tag post.image_url.to_s, :alt =>"" %>
          <%= link_to('read more', post_path(post)) %></p>
          <% if me? %>
            <%= link_to 'Delete Post', post_path(post), method: :delete %>
            <%= link_to 'Edit Post', edit_post_path(post) %>
          <% end %>
        </article>
        <% end %>
      </div><!-- /span12 -->
    </div><!-- /row-fluid -->
  </div><!-- /bl-content -->
  <span class="bl-icon bl-icon-close"></span>
</section>

app/views/home/_contact.html.erb
<section>
  <div class="bl-box", id="about">
    <h2 >Contact Me</h2>
  </div>
  <div class="bl-content">
    <div class="row-fluid">
      <div class="span12">
        <h2>Get in touch</h2>

        <p>
          <p>jonfriese33@email.com | Seattle, WA</p>
        </p>

        <p>
          <a href="https://www.linkedin.com/pub/jon-friese/83/b6/4b8/" class="social-network linkedin"></a>
          <a href="https://github.com/jonfriese" class="social-network github"></a>
          <a href="https://twitter.com/JonFriese33" class="social-network twitter"></a>
          <a href="https://www.facebook.com/jon.friese.5" class="social-network facebook"></a>
        </p>

      </div>
    </div>
    <span class="bl-icon bl-icon-close"></span>
  </section>

app/views/home/_portfolio.html.erb
<section id="bl-work-section">
  <div class="bl-box", id="portfolio">
    <h2 >Latest Works</h2> <!-- class="bl-icon bl-icon-works"-->
  </div>
  <div class="bl-content">
    <h2>Some Recent Personal Projects</h2>
    <p>Most of my work is done in Rails. Here are some of the the projects I have been working on. They are all open-source so feel free to contribute. Send me a push request!</p>
    <p></p>
    <p></p>
    <p></p>
    <div class="row-fluid">
      <div class="span4">
        <ul id="bl-work-items" style="list-style: none;">
          <li data-panel="panel-1"><a href="#"><%= image_tag("job-search.png") %></a></li>
        </ul>
        <p>Job Search</p>
      </div>
      <div class="span4">
        <ul id="bl-work-items" style="list-style: none;">
          <li data-panel="panel-2"><a href="#"><%= image_tag("project1.jpg") %></a></li>
        </ul>
        <p>Link Sensei</p>
      </div>
    </div><!-- /row-fluid -->
  </div><!-- /bl-content -->
  <span class="bl-icon bl-icon-close"></span>
</section>

app/views/home/_project_description.html.erb
<div class="bl-panel-items" id="bl-panel-work-items">
  <div data-panel="panel-1">
    <div class="row-fluid">
      <div class="span8 offset2 tweak">
        <%= image_tag("job-search.png") %>
        <br>
        <br>
        <h4>Project Overview</h4>
        <p>This is a project I began to help aide me in my job search.</p>
        <h4>Project Details</h4>
        <p>It allows me or whoever uses it to search multiple niche job boards at once. It does this by combining search results from several different APIs and RSS feeds </p>
      </div><!-- /span8 -->
    </div><!-- /row-fluid -->
  </div><!-- /panel1 -->
  <div data-panel="panel-2">
    <div class="row-fluid">
      <div class="span8 offset2 tweak">
        <%= image_tag("project1.jpg") %>
        <br>
        <br>
        <h4>Project Overview</h4>
        <p>LinkSensei is a project I began with two other classmates in the 4th week of Codefellows.</p>
        <h4>Project Details</h4>
        <p>LinkSensei currently gives you a way to easily group bookmarks. A user can create containers for links, add descriptions, add links to a staging area, and move links to appropriate containers. Looking forward, we plan to implement a sharing feature as well as create a Google Chrome extension. </p>
      </div><!-- /span8 -->
    </div><!-- /row-fluid -->
  </div><!-- /panel1 -->
  <nav>
    <span class="bl-next-work">&gt; Next Project</span>
    <span class="bl-icon bl-icon-close"></span>
  </nav>
</div><!-- /panel-items -->

app/views/home/index.html.erb
<h1>Welcome!</h1>
<h2>Hello. I'm Jon. I'm currently participating in Code Fellows' Ruby on Rails bootcamp.</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Jon Friese</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">


	<%= stylesheet_link_tag "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <link rel="shortcut icon" href="favicon.ico">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-57-precomposed.png">

  </head>

  <body>



  	<div class="container">

  		<div id="bl-main" class="bl-main">

  			<%= render 'about' %>

  			<%= render 'portfolio' %>

  			<%= render 'blog' %>

  			<%= render 'contact' %>

  			<%= render 'project_description' %>


  		</div><!-- /bl-main -->

  	</div> <!-- /container -->


  	<%= javascript_include_tag "jquery-1.8.2.min.js" %>
  	<%= javascript_include_tag "bootstrap.min.js" %>
    <%= javascript_include_tag "modernizr.js" %>
  	<%= javascript_include_tag "boxlayout.js" %>

  	<script type="text/javascript">
  	$(function() {
  		Boxlayout.init();
  	});
  	</script>
  </body>
</html>

app/views/layouts/post_create.html.erb
<h1>New Post</h1>

<%= render 'posts/form' %>

<%= link_to 'Back', posts_path %>

app/views/layouts/post_edit.html.erb
<h1>EDIT</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/layouts/post_show.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<div class="bl-main", id="blog_show">
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.present? %>
        <%= current_user.name %>
        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%- resource_class.omniauth_providers.each do |provider| %>
          <%= link_to image_tag("sign_in_twitter.png", alt:'twitter', id:"twitter"), omniauth_authorize_path(resource_name, provider) %>
        <% end -%>
      <% end %>
    </ul>
  </div> <!-- /.navbar-collapse -->
  <div class="row-fluid">
    <div class="span12">
      <article>
        <h2><center><%= @post.title %><center></h2>
        <center><p style="width: 50%;"><%= @post.body%></p></center>
      </article>
      <hr>
    </div><!-- /span12 -->
  </div><!-- /row-fluid -->
  <h3>COMMENTS</h3>
  <% @post.comments.each do |comment| %>
  <tr id="<%= dom_id(comment) %>">
    <h3><%= comment.content %></h3>
    <div class="nav">
      <% if policy(comment).destroy? %>
      <%= link_to 'Destroy', post_comment_path(@commentable, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  <% end %>

  <% if current_user.present? %>
    <h3>ADD A COMMENT</h3>
    <%= render 'comments/form' %>
  <% else %>
    <p> You must be signed in to comment! <p>
  <% end %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to_function "Back", "history.back()" %>
</div>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area(:body, rows: 10) %>
  </div>
  <div>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<% if @project.errors.any? %>
<div id="error_explanation">
 <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

 <ul>
   <% @project.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
   <% end %>
 </ul>
</div>
<% end %>

<div class="field">
 <%= f.label :name %><br />
 <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :technologies_used %><br />
  <%= f.text_area(:technologies_used, rows: 2) %>
</div>

<% if policy(Post).publish? %>
<div class="field">
  <%= f.label :published %>
  <%= f.check_box :published %>
</div>
<% end %>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form" %>

<%= link_to "Cancel", :back %>

app/views/projects/index.html.erb
<h1>Portfolio</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</table>

<% @projects.each do |project| %>
<div class="project" id="<%= dom_id(project) %>">

  <h3><%= project.name %></h3>

  <div class="nav">

    <%= link_to 'View Project', project %>

    <% if policy(project).update? %>

    | <%= link_to 'Edit', edit_project_path(project) %> |

    <%= link_to 'Publish', project_path(project, project: { published: true }),
    method: :put %> |

    <% end %>

    <% if policy(project).destroy? %>
    <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>

    <% end %>
  </div>
</div>
<% end %>

<br />

<% if policy(Project).create? %>
<%= link_to 'New Project', new_project_path, class: "btn" %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render "form" %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @project.name %></h2>
<div>
<p>Technologies used: <%= @project.technologies_used %>
</div>
<% @comments.each do |comment| %>
  <tr id="<%= dom_id(comment) %>">
    <td><%= comment.content %></td>
  </tr>
<% end %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

<%= render 'comments/form' %>